
package edu.javacourse.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegionServiceImplService", targetNamespace = "http://webservice.javacourse.edu/", wsdlLocation = "http://localhost:8888/ws/regionService?wsdl")
public class RegionServiceImplService
    extends Service
{

    private final static URL REGIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName REGIONSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.javacourse.edu/", "RegionServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ws/regionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        REGIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RegionServiceImplService() {
        super(__getWsdlLocation(), REGIONSERVICEIMPLSERVICE_QNAME);
    }

    public RegionServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public RegionServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, REGIONSERVICEIMPLSERVICE_QNAME);
    }

    public RegionServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public RegionServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegionServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegionService
     */
    @WebEndpoint(name = "RegionServiceImplPort")
    public RegionService getRegionServiceImplPort() {
        return super.getPort(new QName("http://webservice.javacourse.edu/", "RegionServiceImplPort"), RegionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegionService
     */
    @WebEndpoint(name = "RegionServiceImplPort")
    public RegionService getRegionServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.javacourse.edu/", "RegionServiceImplPort"), RegionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw REGIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return REGIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
