
package edu.javacourse.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegionService", targetNamespace = "http://webservice.javacourse.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegionService {


    /**
     * 
     * @param arg0
     * @return
     *     returns edu.javacourse.webservice.Region
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegionByName", targetNamespace = "http://webservice.javacourse.edu/", className = "edu.javacourse.webservice.GetRegionByName")
    @ResponseWrapper(localName = "getRegionByNameResponse", targetNamespace = "http://webservice.javacourse.edu/", className = "edu.javacourse.webservice.GetRegionByNameResponse")
    @Action(input = "http://webservice.javacourse.edu/RegionService/getRegionByNameRequest", output = "http://webservice.javacourse.edu/RegionService/getRegionByNameResponse")
    public Region getRegionByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<edu.javacourse.webservice.Region>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRegions", targetNamespace = "http://webservice.javacourse.edu/", className = "edu.javacourse.webservice.GetAllRegions")
    @ResponseWrapper(localName = "getAllRegionsResponse", targetNamespace = "http://webservice.javacourse.edu/", className = "edu.javacourse.webservice.GetAllRegionsResponse")
    @Action(input = "http://webservice.javacourse.edu/RegionService/getAllRegionsRequest", output = "http://webservice.javacourse.edu/RegionService/getAllRegionsResponse")
    public List<Region> getAllRegions();

}
